language: ruby
rvm:
- 2.4.1
addons:
  postgresql: '9.3'
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
env:
  global:
#    - secure: r3FzHlkUHZl0YDwrYiEXBqsTCTD9LJsm4MqY5hPsu/5egB7BkhPIUH0CYGCO/G/i3GZK6T3PHCQ3bDLx5nQQDEnQkMPWlhWGMkpdDTpNeMzsCjQN6B8kgHzH+GruGq2mlgZ7uWcGLoJC8d+nb20vdBxFHlh0XcGm2h+s7yEAwJplnqrw95F5yyfs8tORIhAG0Se5OXv0n3YgvbU5czcCr3MadqdX8sy+DiBvwG8BEImB2a5gGIu8MJkRZ2XVKEXYT+Nit9I3WM1ehX1lSIeudv+xN454nQM9Is+u0MFbyQxCPEJA1YzHyOVKBQ1/JmKbK+CeBow9c1OtRlLYJ9EbkPMidYB4GYgdBtW39LY6ZYk4bYJXJ3X1SrlHvx6JP9FkYaBbfcQGkRCStg+tN4WLqnUitVl9shglQSZmTo7/E5bh3xL2jiDL1Zh4OQEOFVX7P+qWTOVr2+H5XDHzyv6RPOHyU4kGbyUfARfmmdDbXDHvLmtQgJ64qbpNvVjp3K05Nq0DB827uNQN16DM9qKi/54bWzflSr202F60WKJM/YbQd8cAF+mJC+MG7dGdvLNSOFd6G7E8sYjYa95oMBxWs2zP/q7HM97bMWJ2Aalrpup1BC5gcnTDiUBuxpImuFj7l7hsPmYb9R5tWauHam1u4uPAkFYCKNdGm+8DwPyxr4Y=
    - YCBA_TEST_SOLR_URL=http://10.5.96.187:8983/solr/ycba-collections_dev1
    - secure: 43n4FQ3AeJASsJlza/zRcOJq1I+dpHv8Pln4Xg+cqyG7pblMtd7J3RF4P9P3NMSq0Qor0izIo1Iu7XGszrBvTqWS7yWTpZAVr4RNn1qEIYpMOo9RhXySOyupc2yj2veyUHVW/OMSgVBFBT0Eyz5d//cZPTB4nG3Ogh49qF2F4TIYnMSL2N1EhZkZfuw8vSMCfIvfQA3F8lHHY7Z+bwNWvp+R8yJzzTXv5UA+kERP07QK5IAHx0YNY598iFUpfzRokbETDG8WwpXXHdY+1g+9Uriku5El6Xiya0MtpguWXrWLbWrRfr6M+zNUkGexidQbLUjsM72OPVV9dgK0ykui5LvwnPRxZjgCZzNZHM1uvUpDuZsNWhtDQddrq+LDLSsMsp+YDeQB4NjvjJvFSZ1CIWDOvi5wUvxcPDd1bpVrZ18l82aVJmyI5PsEW8tQZ/FqnNmB32CscqELpQeSLuu39yIIIvC1XukDGmKa+wYkNbM4ExWitYimXeQLbla1mQ/ZrjpMMWAgVyYtHafAs79wBOYWdAF+2WKB6NQb+/FGDsCjwwBhrGxXJ5QrmU4hfsxAd6aI3H/8DiRzCZAvJ/4fmUXeG9NBlV2RVw/bwEP+ASmi6crPsn+kTQf4JAIYF2SLHriS738f2erOYS97KnaFT97fRbQkddEhUGt9p7R9orI=
deploy:
  provider: heroku
  app:
    master: ycba-collections-dev
  api_key:
    secure: 95xUwufKAW+qjy25RZy22u+O/UifXRtMDM2J/dXjwEsjkb9uK0tv0qrbYMCOEnmwi68YvecQ2HsI8f223Rx6btr1XyRpSLFuZioTOEekfG+WS9bWX75yRjTvvgLOgHMH+Y2l8frbKH9EcJw+jectIxwLKUKJ/1U0PBRogqaRL4+e9OlNPJnHxDixb9ZPQsZJ/PhJHWM8M+4xVGg9itKOHfLyu5j6j3ZYahRfcLaa1yVzfwf2F6xBKkmCiQWyDFfndBuEs8zJ80jiaIfl4PV7rAcntiUJrpA8HJunok5AmNYitllEeKjdWvVoaOPBdyx06pTTm6px6BjHxuXbXNgzJNfQHplprR8Wg7tLIrPngJxOqr5vHdTKLkgSpjaVZoFKz7VYEuI2xztmCI3P7eV+EkrP3HxmE3icktPbEqCpcyrRAq2Vcp7yuEZt3hW/vPy6h3Q2OZWGFIzF3b7GtmKvFdtQQa8k/ENlgaWQ6fSceuNdnq+/UECF78PM/uYOp3pRgOKhf50vBLxAa8AWc/A17/3MQ5vaJ6lMXbE0u4g9AeNgDhcTgR29MsQ0HpY3g+IrzSlxaVTgZBgf1uJ8voIrYQa6ogg7HsLF6EEXwJNaqwVAtlEgvZSm5siOMjmDjmo+fStzki2yUx7kXd3ZvFh6qw20lNG4qjcOCLFdtGB28wE=
  on: solr_from_camel