language: ruby
rvm:
- 2.3.1
addons:
  postgresql: '9.3'
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
env:
  global:
    secure: U40TKd2z1yQoYBfN2yi814429VrXcIxpc6t2tyy/Vuy2gL9qifV/6IHXTvg8tgbTUNOwqTMR/hOmw0FQg6AdZiqIHCFsRd9Zz1Ewecbb04Q3YMlvlBYfxkncaarLv3l1FIdF3P/fMHhBvwDAqaMPoaMJgIDKkv6XbwFSlgN61isp/d2NURMB+yj2Qo7HmdzyuA64L224Kqprh8yDC2B/t8TLMJjFcQVwDFfnLeTnmZG1k/UQ2pZuWJzihWLEo4tOXt7u6pXZY06gB2NEvkQFHj3QpkB8Awkynsdg0e4n+OZQcCPrJMnpw7d0qYwn4RWgYE0TFQ3qrqSeROUZBt8a1Va88+/Wr1onSvbkslfgiTMelYW/WmMSDuGQM2/OD9pf5CPY854SnsIiNVRzEg2RqeqAwCmosa1iu2bGKQ6ehLPgX4zo+FJV6BRMf8wl5fqrRaT2TsuaFXDCYBTV82IoyruSya0iD8cJ73rXAGGLqz22RcBRG8Cugdco3VcOgTImLUlOBCI+RYuI5AEViLBSvQA607xisIKSU7YXz85433/kd8xQW55l2ITLoxZ51e19xx5hpCS0CiFdEqhK8QQuYWvjVeUZPBQSI8a5KgYzVmndPxf+aGdAsSci5gN6UeEIQMXN6CEMkBQtyZw7fSpwlMG7gshn0S2tu5TyR2oIp9s=
deploy:
  provider: heroku
  app:
    master: ycba-collections2-staging
  api_key:
    secure: 95xUwufKAW+qjy25RZy22u+O/UifXRtMDM2J/dXjwEsjkb9uK0tv0qrbYMCOEnmwi68YvecQ2HsI8f223Rx6btr1XyRpSLFuZioTOEekfG+WS9bWX75yRjTvvgLOgHMH+Y2l8frbKH9EcJw+jectIxwLKUKJ/1U0PBRogqaRL4+e9OlNPJnHxDixb9ZPQsZJ/PhJHWM8M+4xVGg9itKOHfLyu5j6j3ZYahRfcLaa1yVzfwf2F6xBKkmCiQWyDFfndBuEs8zJ80jiaIfl4PV7rAcntiUJrpA8HJunok5AmNYitllEeKjdWvVoaOPBdyx06pTTm6px6BjHxuXbXNgzJNfQHplprR8Wg7tLIrPngJxOqr5vHdTKLkgSpjaVZoFKz7VYEuI2xztmCI3P7eV+EkrP3HxmE3icktPbEqCpcyrRAq2Vcp7yuEZt3hW/vPy6h3Q2OZWGFIzF3b7GtmKvFdtQQa8k/ENlgaWQ6fSceuNdnq+/UECF78PM/uYOp3pRgOKhf50vBLxAa8AWc/A17/3MQ5vaJ6lMXbE0u4g9AeNgDhcTgR29MsQ0HpY3g+IrzSlxaVTgZBgf1uJ8voIrYQa6ogg7HsLF6EEXwJNaqwVAtlEgvZSm5siOMjmDjmo+fStzki2yUx7kXd3ZvFh6qw20lNG4qjcOCLFdtGB28wE=
