language: ruby
rvm:
- 2.3.1
addons:
  postgresql: '9.3'
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
env:
  global:
    secure: U40TKd2z1yQoYBfN2yi814429VrXcIxpc6t2tyy/Vuy2gL9qifV/6IHXTvg8tgbTUNOwqTMR/hOmw0FQg6AdZiqIHCFsRd9Zz1Ewecbb04Q3YMlvlBYfxkncaarLv3l1FIdF3P/fMHhBvwDAqaMPoaMJgIDKkv6XbwFSlgN61isp/d2NURMB+yj2Qo7HmdzyuA64L224Kqprh8yDC2B/t8TLMJjFcQVwDFfnLeTnmZG1k/UQ2pZuWJzihWLEo4tOXt7u6pXZY06gB2NEvkQFHj3QpkB8Awkynsdg0e4n+OZQcCPrJMnpw7d0qYwn4RWgYE0TFQ3qrqSeROUZBt8a1Va88+/Wr1onSvbkslfgiTMelYW/WmMSDuGQM2/OD9pf5CPY854SnsIiNVRzEg2RqeqAwCmosa1iu2bGKQ6ehLPgX4zo+FJV6BRMf8wl5fqrRaT2TsuaFXDCYBTV82IoyruSya0iD8cJ73rXAGGLqz22RcBRG8Cugdco3VcOgTImLUlOBCI+RYuI5AEViLBSvQA607xisIKSU7YXz85433/kd8xQW55l2ITLoxZ51e19xx5hpCS0CiFdEqhK8QQuYWvjVeUZPBQSI8a5KgYzVmndPxf+aGdAsSci5gN6UeEIQMXN6CEMkBQtyZw7fSpwlMG7gshn0S2tu5TyR2oIp9s=
deploy:
  provider: heroku
  app:
    master: ycba-collections2-staging
  api_key:
    secure: c2u4TqDz5UtMN0Y9drpjPfxbRO0KiHvMSxCvfhvdALCJrnP+Xj0d3Oti64RC5mHGwX/1M9DxE6vrDyw6t/re+EyaLKd/QyuO+99cTvfL+0U/Zl6nSDA6DpVj2isGK0UjKiTeq5CkLzHRYTP4fzf6HyqtZFr+CYYynDxBfLfIEjYk+3yAjNEqY7IdYYGKOTjtu8P89rIe9Pe0zxNNn7iUGOmxMLoXuUoVLjVl6H/pBarwQh1RPtLFc93ORI058vcCfVXmds9m7LHMQydIAcjzg3ihix30xSNDsO203HUPkZuWvLOe8dwalesLBmbwPckmWA0+pl9+40ytZfKyOavKm8Xl37Q6cis8PaV7aHfjaGpN/qHchfrLwHBE47gH94RgUJV5WVY9bILYpYI6ezjMhfp7/jf16ipQeEGO+woVdFD4YbVaQmuHc1xo1AG+lE7wMX07CGZhf0zV8TnRb8QWcScVjG++ugdmp2W4PvfvdjNhAL/OJTMKUuLOMZXlnO1uzaK/9D7Gjf1J5tOk6gl9n6K39ykVrDWlmWI6xWc1tNqtTgmfryiSbLpu8lBdBW9MDknoewT7clKm7twusf7A6CBc8O0C7sPCP61xtBUq3voXWnTvUi7/YERieKr5GqwsD1Pmufy3L9AMe2eBaItk1OYVE7NTDnRt/xnM+CDVbeU=
