language: ruby
rvm:
- 2.4.4
before_install:
  - cp config/ciaindex-britishart-yale-edu.pem config/ciaindex-britishart-yale-edu.pem
  - more config/ciaindex-britishart-yale-edu.pem | sudo tee -a /etc/ssl/certs/ca-certificates.crt
addons:
  postgresql: '9.6'
  apt:
    packages:
      - ca-certificates
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.pipeline.travis config/database.yml
env:
  global:
  - secure: NmOgLnTJi2KpAPBAWwYAw9X4+SsN3X6IP4qpSDK+fyu30e91wic8o0/WMaNIztOzJO5/uGDydAxlF9p61CrtRFYgy7LXj+ThAa0yhBChxsax3CVdCfJ7fTHA2vnhCEKd/yb+WNk0zGvMARzS+JDT+R8KRFa6/3LJjKcbfEZ8wiwz1MLRiMxhfAj5v7MrXowWHlT0Vfx1fwIFNps6Gf/jO7WBSeqKF16UYhpflwzrAO7BXJERvZ0ur/Mdo2OdIGihn+ekdh87rebU75BKN/UpyRxztP0d5jQzYnB0lU+K2SIe6V9Wk7jMf4+Z7L9DkvnloVaU6D4obGjD3iddC3hXhq9OCmhaWT+GamzZpIMSvSEgLthAYBfSdJkv+uVeMTtQmEGkRBT6pHfvpYPfaKW6+0Yxbqbau9Rl2n6jKy6nlQH4d6yY6qrPdXKnpIZ5wQ53oi5muUOepL1Hj+a8fXPAfsWlVzFDbkBDrI97OfWEeg+0u0y4qxKumK6kUBseedyfn+bnBG8AiY8Cv+jAU8TbKaJjvRo8K/V8vJmL7xSFZh+SyiTuevjdGaIw8b/0mIEJkuNk56w7kBLS8do72VOEJ6daR1FwHT4G7pRaqw8TuqZ7EDWG1jZM/MUe82Yp8YDEnNCT4DbbqOIo3rOR753ECvR695wxXZDqHxLkAHn2FE4=
  - secure: r3FzHlkUHZl0YDwrYiEXBqsTCTD9LJsm4MqY5hPsu/5egB7BkhPIUH0CYGCO/G/i3GZK6T3PHCQ3bDLx5nQQDEnQkMPWlhWGMkpdDTpNeMzsCjQN6B8kgHzH+GruGq2mlgZ7uWcGLoJC8d+nb20vdBxFHlh0XcGm2h+s7yEAwJplnqrw95F5yyfs8tORIhAG0Se5OXv0n3YgvbU5czcCr3MadqdX8sy+DiBvwG8BEImB2a5gGIu8MJkRZ2XVKEXYT+Nit9I3WM1ehX1lSIeudv+xN454nQM9Is+u0MFbyQxCPEJA1YzHyOVKBQ1/JmKbK+CeBow9c1OtRlLYJ9EbkPMidYB4GYgdBtW39LY6ZYk4bYJXJ3X1SrlHvx6JP9FkYaBbfcQGkRCStg+tN4WLqnUitVl9shglQSZmTo7/E5bh3xL2jiDL1Zh4OQEOFVX7P+qWTOVr2+H5XDHzyv6RPOHyU4kGbyUfARfmmdDbXDHvLmtQgJ64qbpNvVjp3K05Nq0DB827uNQN16DM9qKi/54bWzflSr202F60WKJM/YbQd8cAF+mJC+MG7dGdvLNSOFd6G7E8sYjYa95oMBxWs2zP/q7HM97bMWJ2Aalrpup1BC5gcnTDiUBuxpImuFj7l7hsPmYb9R5tWauHam1u4uPAkFYCKNdGm+8DwPyxr4Y=
  - secure: 43n4FQ3AeJASsJlza/zRcOJq1I+dpHv8Pln4Xg+cqyG7pblMtd7J3RF4P9P3NMSq0Qor0izIo1Iu7XGszrBvTqWS7yWTpZAVr4RNn1qEIYpMOo9RhXySOyupc2yj2veyUHVW/OMSgVBFBT0Eyz5d//cZPTB4nG3Ogh49qF2F4TIYnMSL2N1EhZkZfuw8vSMCfIvfQA3F8lHHY7Z+bwNWvp+R8yJzzTXv5UA+kERP07QK5IAHx0YNY598iFUpfzRokbETDG8WwpXXHdY+1g+9Uriku5El6Xiya0MtpguWXrWLbWrRfr6M+zNUkGexidQbLUjsM72OPVV9dgK0ykui5LvwnPRxZjgCZzNZHM1uvUpDuZsNWhtDQddrq+LDLSsMsp+YDeQB4NjvjJvFSZ1CIWDOvi5wUvxcPDd1bpVrZ18l82aVJmyI5PsEW8tQZ/FqnNmB32CscqELpQeSLuu39yIIIvC1XukDGmKa+wYkNbM4ExWitYimXeQLbla1mQ/ZrjpMMWAgVyYtHafAs79wBOYWdAF+2WKB6NQb+/FGDsCjwwBhrGxXJ5QrmU4hfsxAd6aI3H/8DiRzCZAvJ/4fmUXeG9NBlV2RVw/bwEP+ASmi6crPsn+kTQf4JAIYF2SLHriS738f2erOYS97KnaFT97fRbQkddEhUGt9p7R9orI=
deploy:
  provider: heroku
  app:
    master: ycba-collections-dev
  api_key:
    secure: ru9RLsTpUuvknqZVeSfY6t15h0yFw42o4MtCOwStXGg4y80V/3OrKSFZvEeWujlJx0XA+5MlBTWBe0WqQ66tFIF8yHA+JgRmN0krUrhn28503HObzC3c9cujF1CiWkKYHWe3yZV5nG9aOjjTPcINR5AW+P/7VftW5k953usL4tGjonH72M+Z2iRZQSz+ANt1bhvmj2wbJ2S8yzsv5Y68mFZ1x1QeAWyK5vFiz+Uk5FmXxjj7cdIsRGgxoeLAfbtsZG/me8P1NkdpBgTWuT0JBWkCy+jC+H+OiU/8akK5c71temVvAWhbOM/ac2c6OHHV7ucMpz76bbHC4nbPdrBdjK3MpzmxT5xj4rIBD2C7G9CcsW/KYLKh9hYtbjCTNC30b/HodDrwrzhuXKLda5L3ddIlDfab/zJko+4cLcfMt6qBier0SeW/Ae5xDREK6+IOKWqfkyND4hlT5/ToTQR26/aajxRuhGM9NqoFDZS9xnZmpbDnURZa/8OlP6M/O+A275nOQscZeMv8cHyaAPK0tQM/X8yGyF3r2uIASydCDN9zT6jJdIEqFJA9M2Jss9cui2W+RsdkB0itjJJjCSyRdZnSaE5vgUD9m2BV/gZ10XmjXPCkq9qe43dHQMUBymiGyiCdcmG+29FyaW8q7fvknLM0wzpf/apeME/AKQI1Sa8=
